### ISSUE TITLE
Add support for custom properties

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/hubspot-plugin#1]
It would be nice if the plugin had a config option to support custom properties, as and when they're added in `$identify` calls, as well as [added on Hubspot](https://knowledge.hubspot.com/crm-setup/manage-your-properties?_ga=2.135700019.341006870.1586180142-500942594.1573763828#create-custom-properties)

**Comment by kpthatsme** [comment]
Done https://github.com/PostHog/hubspot-plugin/pull/3
