### ISSUE TITLE
"Additional PostHog to HubSpot property mappings" Not working

### ISSUE THREAD

**Issue by oneshot-engineering** [PostHog/hubspot-plugin#15]
Am using cloud version of plugin. I used following PostHog property created_at and mapped with a Hubspot property ph_signup_date like below on an identify event. I see that Contact is created but the customer properties aren't being synced

created_at:ph_signup_date

**Comment by marcushyett-ph** [comment]
@oneshot-engineering are you seeing any specific error messages from the plugin? Is this for new contacts or updating existing contacts?

**Comment by polavenki** [comment]
@marcushyett-ph  -  I am seeing the same errors that are mentioned in the other issue. It happens for both create or update happens for only date fields. 

I think that's because of Hubspot needs the time to be 0:0:0:0 time. Should be easily reproducible for created_at field.

**Comment by marcushyett-ph** [comment]
Thanks, will take a look.

**Comment by marcushyett-ph** [comment]
I've special cased `created_at` as well as `sent_at`, this should now work.
