### ISSUE TITLE
If `$identify`ing the same person, update instead of creating a new entry in Hubspot

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/hubspot-plugin#2]

**Comment by kpthatsme** [comment]
@neilkakkar in theory Hubspot should be [automerging](https://knowledge.hubspot.com/crm-setup/deduplication-of-contacts-companies-deals-tickets#deduplicate-contacts-by-email-address) contacts based on their email address - did you happen to see examples where this wasn't happening?

**Comment by neilkakkar** [comment]
Oh, interesting! Didn't notice that. It was a request from a customer, but now I guess they weren't sending the email every time. (the identifier was other than email?)
