### ISSUE TITLE
How to reference event name in configuration?

### ISSUE THREAD

**Issue by doppleware** [PostHog/hubspot-plugin#46]
I am using the Hubspot app. However, I need to trigger creating/updating contacts via a different event than $identify which seems to be the default option (and which I verified works well)

My problem might be a newbie issue but I really don't know how to refer to the event. Should I prefix the event name with a dollar sign? How to I handle the spaces in the event name? Should they convert to underscores automatically?

Would be great in general to have an example in the docs for referring to an event other than $identify

Thanks!
Roni

**Comment by MarconLP** [comment]
Hey @doppleware, you'll need to specify the exact event. To figure out the correct event value, you can open the JSON version of the event in the Activity tab to see the exact value.
![2024-02-05 at 15 14 23@2x](https://github.com/PostHog/hubspot-plugin/assets/13001502/13736c2c-5426-41df-874a-8537781b3f55)
